/**
 * Google Place data utility for build time.
 *
 * Reads scraped data from src/data/google-place-data.json (generated by
 * scripts/fetch-google-reviews.mjs before each build).
 *
 * Falls back to static data from google-reviews.json if the scraped file
 * is missing.
 */

export interface GoogleReview {
  author: string;
  authorUrl?: string;
  profilePhoto?: string;
  rating: number;
  text: string;
  time: string;
  timestamp?: number;
}

export interface GooglePlaceData {
  rating: number;
  reviewCount: number;
  name: string;
  url: string;
  reviews: GoogleReview[];
}

// Import static reviews as fallback
import staticReviewsData from '../data/google-reviews.json';

import { readFileSync } from 'fs';
import { join } from 'path';

const MAPS_URL = 'https://www.google.com/maps/place/Hercules+Merchandise+NL/data=!4m2!3m1!1s0x8565f6c310e115b1:0xe2cb88b822f6b3c4';

// Read scraped data (generated by scripts/fetch-google-reviews.mjs before build)
function loadScrapedData(): any {
  try {
    const filePath = join(process.cwd(), 'src/data/google-place-data.json');
    return JSON.parse(readFileSync(filePath, 'utf-8'));
  } catch {
    return null;
  }
}

// Default fallback values
const FALLBACK_DATA: GooglePlaceData = {
  rating: 4.9,
  reviewCount: 17,
  name: 'Hercules Merchandise NL',
  url: MAPS_URL,
  reviews: staticReviewsData.reviews as GoogleReview[]
};

// Cache the result during build
let cachedData: GooglePlaceData | null = null;

/**
 * Get Google Place data (rating, review count, reviews).
 * Reads from the pre-scraped JSON file generated before build.
 */
export async function getGooglePlaceData(): Promise<GooglePlaceData> {
  if (cachedData) {
    return cachedData;
  }

  const scrapedData = loadScrapedData();

  if (scrapedData && typeof scrapedData.rating === 'number') {
    cachedData = {
      rating: scrapedData.rating,
      reviewCount: scrapedData.reviewCount || FALLBACK_DATA.reviewCount,
      name: scrapedData.name || FALLBACK_DATA.name,
      url: scrapedData.url || MAPS_URL,
      reviews: (scrapedData.reviews?.length > 0 ? scrapedData.reviews : staticReviewsData.reviews) as GoogleReview[]
    };
    console.log(`[GooglePlaces] Using scraped data: ${cachedData.rating} stars from ${cachedData.reviewCount} reviews (scraped ${scrapedData.scrapedAt || 'unknown'})`);
  } else {
    console.warn('[GooglePlaces] No scraped data found. Run: node scripts/fetch-google-reviews.mjs');
    console.warn('[GooglePlaces] Using fallback values');
    cachedData = FALLBACK_DATA;
  }

  return cachedData;
}

/**
 * Get the star rating as a display string (e.g., "4.9")
 */
export function formatRating(rating: number): string {
  return rating.toFixed(1); // English format: 4.9
}

/**
 * Get the review count as a display string (e.g., "100+ Reviews")
 */
export function formatReviewCount(count: number): string {
  if (count >= 1000) {
    return `${Math.floor(count / 1000)}k+ beoordelingen`;
  }
  return `${count}+ beoordelingen`;
}
